AWSTemplateFormatVersion: "2010-09-09"
Description: Static frontend for notifications
Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: 'davidj-notifications-ui'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref StaticWebsiteBucket
                - /*
            Principal: '*'
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - StaticWebsiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - StaticWebsiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content